---
title: "Spatial Covariance"
author: "Yi Li"
date: "June 18, 2016"
output: pdf_document
---

## 1. Covariance by Threshoulding

Reproduce on Temp based on GCM

### 1.1 Without Threshoulding

```{r}
setwd("/home/liyi/Documents/esdcybersees")
library(maptools)
data(wrld_simpl)
load("lonlat.RData")
```


```{r,include=FALSE}
#============================ Plot EOF ==============================================
V5=read.table("./results_eof/ta_month_1_svd_eigenvectors_top_5.txt",sep=",")
L=read.table("./results_eof/ta_month_1_svd_eigenvalues.txt",sep=",")


V5=V5[,ncol(V5):1]
L=rev(L[,1])
L.sum=sum(L[L>0])
L5=L[1:5]


eof1=matrix(V5[,1],144,90,byrow = T)
eof2=matrix(V5[,2],144,90,byrow = T)
eof3=matrix(V5[,3],144,90,byrow = T)
eof4=matrix(V5[,4],144,90,byrow = T)
eof5=matrix(V5[,5],144,90,byrow = T)


# Lon=ifelse(lon<=180,lon,lon-360)
# Lon=Lon[c(73:144,1:72)]

par(mfrow=c(3,2),
    #    oma = c(1,1,0,0),
    mar = c(2,2,2,2))

image(Lon,lat,eof1[c(73:144,1:72),],main=paste0(round(L5[1]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof1[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof2[c(73:144,1:72),],main=paste0(round(L5[2]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof2[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof3[c(73:144,1:72),],main=paste0(round(L5[3]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof3[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof4[c(73:144,1:72),],main=paste0(round(L5[4]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof4[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof5[c(73:144,1:72),],main=paste0(round(L5[5]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof5[c(73:144,1:72),],add=T,col="purple")

plot(1:10,L[1:10]/L.sum,type="o",col="blue",main="Variance Explained")

```

### 1.2 With Threshoulding

```{r,include=FALSE}

V5=read.table("./results_eof/ta_month_1_svd_threshold_1_eigenvectors_top_5.txt",sep=",")
L=read.table("./results_eof/ta_month_1_svd_threshold_1_eigenvalues.txt",sep=",")


V5=V5[,ncol(V5):1]
L=rev(L[,1])
L.sum=sum(L[L>0])
L5=L[1:5]


eof1=matrix(V5[,1],144,90,byrow = T)
eof2=matrix(V5[,2],144,90,byrow = T)
eof3=matrix(V5[,3],144,90,byrow = T)
eof4=matrix(V5[,4],144,90,byrow = T)
eof5=matrix(V5[,5],144,90,byrow = T)


# Lon=ifelse(lon<=180,lon,lon-360)
# Lon=Lon[c(73:144,1:72)]

par(mfrow=c(3,2),
    #    oma = c(1,1,0,0),
    mar = c(2,2,2,2))

image(Lon,lat,eof1[c(73:144,1:72),],main=paste0(round(L5[1]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof1[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof2[c(73:144,1:72),],main=paste0(round(L5[2]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof2[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof3[c(73:144,1:72),],main=paste0(round(L5[3]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof3[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof4[c(73:144,1:72),],main=paste0(round(L5[4]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof4[c(73:144,1:72),],add=T,col="purple")

image(Lon,lat,eof5[c(73:144,1:72),],main=paste0(round(L5[5]/L.sum,2)*100,"%"))
plot(wrld_simpl,add=T)
contour(Lon,lat,eof5[c(73:144,1:72),],add=T,col="purple")

plot(1:10,L[1:10]/L.sum,type="o",col="blue",main="Variance Explained")

```


## 2. Spatial Covariance

### 2.1 On Simulate Data

```{r,include=FALSE}
par(mfrow=c(1,1))
n=10
X_label=matrix(1:n^2,n,n,byrow = T)
C=matrix(0,n^2,n^2)

for(i1 in 1:n){
  for(j1 in 1:n){
    for(i2 in 1:n){
      for(j2 in 1:n){
        i=(i1-1)*n+j1
        j=(i2-1)*n+j2
        C[i,j]=exp(-0.4*base::norm(as.matrix(c(i1-i2,j1-j2)),type="2"))
      }
    }
  }
}

library(cape)
image(rotate.mat(C),main="S: Covariance Matrix Structure(decay with distance)")
image(rotate.mat(X_label),main="X: 2D Spatial Stations Labels")
for(i in 1:n){
  for(j in 1:n){
    count=(i-1)*n+j
    text(j/(n-1)-0.1,1-i/(n-1)+0.1,count)
  }
}
```


### 2.2 On Real Data

```{r,include=FALSE}
load("~/Documents/esdcybersees/results_eof/Scov.RData")
image(rotate.mat(S),main="Scov")
load("~/Documents/esdcybersees/results_eof/Scor.RData")
image(rotate.mat(S),main="Scor")
```

